### PR TITLE
explicit cast 

### LINKED ISSUE #5: Cstring to LPCWSTR?
Hi,

I was trying to find a replacement for fsmonitor (and since learned it doesn't work on windows anyway), but I couldn't make fsnotify work and don't know how to fix it in current nim:

```sh
base.nim(54, 37) Error: type mismatch
Expression: getFileAttributesW(addr(x))
  [1] addr(x): ptr WideCStringObj

Expected one of (first mismatch at [position]):
[1] proc getFileAttributesW(lpFileName: LPCWSTR): DWORD
```

This library is probably not actively maintained but any insights are welcome

### PR DESCRIPTION
**Pull request by melMass**
fixes #5

### CODE REVIEW

File: src/fsnotify/base.nim [hunk 1]
```diff
@@ -52,6 +52,7 @@ when defined(windows):
   proc getFileId(name: string): uint =
     var x = newWideCString(name)
     result = uint getFileAttributesW(addr x)
```
Comment (ringabout) [inline src/fsnotify/base.nim]:
```suggestion
```

**Comment by melMass** [comment]
Sorry my formatter changed the whole file and I forgot to pick the deletion!

**Comment by ringabout** [comment]
No problem. Nice work!
